- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221101200508973 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221101200508973 to main

- settingFiles/admx/en-US/VisualStudio.adml
Described values that would configure a machine to receive admin updates from Intune
> Updated descriptions for setup policies

- build/PrepareStagingDirectoryForSelfExtractor.ps1
Update the script's synopsis and description.
> Updated the script's synopsis and description.

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221104104325735 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221104104325735 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221104230058098 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221104230058098 to main

- src/loc/LCL/PLK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221105224143988 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221105224143988 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221108114440442 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221108114440442 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221108234403572 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221108234403572 to main

- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221109114217574 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221109114217574 to main

- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221109234104014 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20221109234104014 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230104114911927 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230104114911927 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230104235059502 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230104235059502 to main

- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230106002721585 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230106002721585 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230301114251214 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230301114251214 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230301234745607 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230301234745607 to main

- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230302114412094 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230302114412094 to main

- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230302235402989 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230302235402989 to main

- settingFiles/admx/VisualStudio.admx
- settingFiles/admx/en-US/VisualStudio.adml
This is related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1689240.
This is the first time that I'm authoring one of these policies.
cc @vijayrkn @curib
> Update to add policy for VS dev tunnels

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230503224112214 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230503224112214 to main

- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230505115252447 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230505115252447 to main

- src/loc/LCL/ITA/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230519224430138 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230519224430138 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230520110911109 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230520110911109 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230529230010571 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230529230010571 to main

- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230613223842153 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230613223842153 to main

- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230614103941155 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230614103941155 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230614224024660 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230614224024660 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230615104037190 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230615104037190 to main

- src/loc/LCL/CSY/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230615223933527 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230615223933527 to main

- settingFiles/admx/VisualStudio.admx
Update DisableVisualStudioDevTunnels to include the enabled and disabled values.
<enabledValue>
<decimal value="1" />
</enabledValue>
<disabledValue>
<decimal value="0" />
</disabledValue>
> Added the enabled and disabled values.

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230802103804381 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230802103804381 to main

- build/build.yml
The Loc team has asked that we run a weekly build to ensure we don't fall of their radar.
> Add a schedule so that the branch is built weekly.

- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230802223850307 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230802223850307 to main

- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230803103957076 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230803103957076 to main

- settingFiles/admx/VisualStudio.admx
- settingFiles/admx/en-US/VisualStudio.adml
Add the AdministratorPromptToClose reg key and explain scaffolding.
To support the admin prompt to close experience, we need to add a group policy to the ADMX and ADML files.
Add the AdministratorPromptToClose policy.
> Add the AdministratorPromptToClose reg key and explain scaffolding.

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230930103844544 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230930103844544 to main

- src/loc/LCL/PLK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230930223912222 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20230930223912222 to main

- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20231001103940542 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20231001103940542 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20231001223958817 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20231001223958817 to main

- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20231002223759766 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20231002223759766 to main

- settingFiles/admx/VisualStudio.admx
- settingFiles/admx/en-US/VisualStudio.adml
Adding `Disable Copilot` and `Disable Copilot for Individuals` policies. These will be used to disable copilot functionality.
- Added policies to admx file
- Added strings to adml file
- Also updated vs versioning string 
The policies
> Add Copilot Settings

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240404104054021 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240404104054021 to main

- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240404223938332 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240404223938332 to main

- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240405105035466 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240405105035466 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240405225807754 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240405225807754 to main

- settingFiles/admx/VisualStudio.admx
- settingFiles/admx/en-US/VisualStudio.adml
Add update notification in VS opt out policy to ADMX and update other aka.ms link to https
Tested locally by following the read.me, checked that the policy applies.
> Add update notification opt out policy

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240826104917460 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240826104917460 to main

- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240826225324000 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240826225324000 to main

- src/loc/LCL/CSY/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240827104851362 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20240827104851362 to main

- settingFiles/admx/en-US/VisualStudio.adml
I missed this value in a previous PR due to a rebase error.  Fix it now.
> Fixed incorrect parameter name.

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20241117113658040 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20241117113658040 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20241116234036694 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20241116234036694 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20241209233722388 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20241209233722388 to main

- src/ADMXExtractor/ADMXExtractor.csproj
Enable source link
Allow debugger to download underlying source files if needed
Add source link package reference to csproj file
[x] Ran `sourcelink test "path to pdb file"` and ensured it passes
[x] Ran end-to-end testing and ensured the file was downloaded from source link
> Enable source link

- settingFiles/admx/en-US/VisualStudio.adml
Update ProductFeedbackDisabled and SurveysDisabled explanation to include the functionality in installer for these policies.
> Update ProductFeedbackDisabled and SurveysDisabled explanation

- src/loc/LCL/ESN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/PTB/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250307113646319 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250307113646319 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CSY/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/FRA/VisualStudio.adml.lcl
- src/loc/LCL/ITA/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/PLK/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250308010136890 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250308010136890 to main

- src/loc/LCL/CHT/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250308114328448 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250308114328448 to main

- src/loc/LCL/CHS/VisualStudio.adml.lcl
- src/loc/LCL/CHT/VisualStudio.adml.lcl
- src/loc/LCL/DEU/VisualStudio.adml.lcl
- src/loc/LCL/JPN/VisualStudio.adml.lcl
- src/loc/LCL/KOR/VisualStudio.adml.lcl
- src/loc/LCL/RUS/VisualStudio.adml.lcl
- src/loc/LCL/TRK/VisualStudio.adml.lcl
LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250919151858472 to main with localized lcls
> LEGO: Pull request from lego/hb_b357b95e-59c7-4dc2-91d5-bbdbb5ee347a_20250919151858472 to main
